export enum ErrorCodeEnum {
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export const HTTP_STATUS_TO_ERROR_CODE: Record<number, ErrorCodeEnum> = {
  400: ErrorCodeEnum.BAD_REQUEST,
  401: ErrorCodeEnum.UNAUTHORIZED,
  403: ErrorCodeEnum.FORBIDDEN,
  404: ErrorCodeEnum.NOT_FOUND,
  409: ErrorCodeEnum.CONFLICT,
  422: ErrorCodeEnum.VALIDATION_ERROR,
  429: ErrorCodeEnum.TOO_MANY_REQUESTS,
  500: ErrorCodeEnum.INTERNAL_SERVER_ERROR,
};
