export const OPERATIONS = {
  APPLICATION_START: 'APPLICATION_START',
  RECEIVE_INBOUND_EMAIL: 'RECEIVE_INBOUND_EMAIL',
  QUEUE_INBOUND_EMAIL: 'QUEUE_INBOUND_EMAIL',
  PROCESS_INBOUND_EMAIL: 'PROCESS_INBOUND_EMAIL',
  RESOLVE_TENANT: 'RESOLVE_TENANT',
  CLASSIFY_EMAIL: 'CLASSIFY_EMAIL',
  CREATE_TASK_FROM_EMAIL: 'CREATE_TASK_FROM_EMAIL',
} as const;
